### ISSUE TITLE
Classe não encontrada

### ISSUE THREAD

**Issue by acezarneto** [raelgc/template#16]
Primeiramente parabéns pelo projeto e confesso que gostei muito quando um amigo meu apresentou este template em 2009 e desde então venho utilizado em meus projetos.

Quanto ao 'defeito' apresentado na versão 2.2, linhas **173** e **184** faltou colocar uma barra invertida **\** no início da classe **InvalidArgumentException**. A falta da barra faz com que PHP interprete como uma classe não encontrada e com a barra corrige o erro exibindo a exceção corretamente, no meu caso.

Abraço.

**Comment by raelgc** [comment]
Oi @acezarneto! Obrigado pelo elogio e por apontar o problema e correção!

Você pode fazer um pull request com a correção? Se não souber como, acredito que se você tentar editar o arquivo aqui na própria interface web do GitHub fará isso automaticamente.

Assim seu nome vai aparecer nos contribuidores automaticamente.

**Comment by raelgc** [comment]
Pronto, arrumado! Obrigado @acezarneto!
