### ISSUE TITLE
Contribuição!!

### ISSUE THREAD

**Issue by condtec** [raelgc/template#23]
Alguns anos atrás, bastante tempo, quando encontrei dificuldade em fazer um site, por nunca gostar de misturar o html com o php tão pouco as complexas framework e templates. Então achei o site do Rael, e esse template, foi muito bom, com o tempo eu fui adicionando, modificando enfim, fazendo minhas altrações de acordo com minhas necessidade! Mudei inclusive o nome dos blocos, mas a maior parte do codigo ainda esta no original. Eu não tenho conhecimento para fazer as modificações e adições aqui, e também existe muitas novidade aqui das quais nem sei, por não acompanhar o site e nem o github.. O legal seria passar as funções a biblioteca para português, para maior entendimento e compreensão do seu funcionamento. Caso queiram que eu exponha o código para pegar algo que seja util adicionar no original eu colocarei a baixo. No mais sou muito grato ao Rael por disponibilizar esse material ao publico, e sem ele nunca estaria satisfeito com meus projetinhos php ahahha!!

**Comment by Valkhan** [comment]
@condtec vi que você tem um repositório que é um fork desta classe, as modificações que você citou estão presentes nela? se sim, eu e o @raelgc podemos dar uma conferida, se puder destacar os pontos de melhoria que realizou também é de grande ajuda.

>  O legal seria passar as funções a biblioteca para português para maior entendimento e compreensão do seu funcionamento.

Acredito que a documentação já resolve esta situação, mesmo porque considerando a questão de compatibilidade com versões anteriores tal modificação poderia ter impactos significativos para quem já utiliza a classe.

Quem sabe um conjunto de exemplos disponibilizado no projeto base não seria mais adequado para tal situação?

**Comment by rafaelkapela** [comment]
Eu uso essa classe, desde sei-la-quando, em vários projetos.
Precisei modificar ela um pouco pra me atender, mas como sou um programador egoísta, me esqueci de fazer commits. Eu gostaria de ajudar, contribuindo financeiramente pro projeto, já que me ajudou tanto...

Como posso fazer isso @raelgc ?

**Comment by Valkhan** [comment]
@rafaelkapela entre em contato com ele por e-mail, clique sobre o perfil dele que tem um e-mail, por lá você pode tratar com mais detalhes.

**Comment by condtec** [comment]
Quando tiver tempo tento fazer isso então! valeu!

**Comment by raelgc** [comment]
@condtec Fico muito honrado pela consideração, mas felizmente já tenho recebido mais do que gasto atualmente, e sentiria que seria injusto receber uma contribuição financeira.

O melhor pagamento - e o que me deixa feliz de verdade! - é ouvir que esta pequena biblioteca tenha te ajudado!

**Comment by condtec** [comment]
Vou colocar meu arquivo aqui, porem esta muito bagunçado, fiz varias modificações mudei por exemplo BEGIN para INI e FIM mudei nome das de algumas funções, etc.. porem no codigo coloquei compressor de jvascrip, html e css, então ficou top, coloquei add string, add outros pedaços fui fazendo de acordo que que eu precisei, ate agora ta funciona mostrar blocos, nao me lembro mais listava blocos e variaveis, mostrava erros etc. estou voltando a programar mais entendo muito pouco de php eu faço muito ctrl+c e crtl+v modifico e vejo os resultados, Então esta uma bagunça, vou anexar aqui mesmo, pois faço menor ideia de como modifica por aqui, caso alguem queira adaptar o codigo ou melhorar!!!

`<?php
 #Grande Rael!! raelcunha.com/template
 #add_string($varname, $string)
class Template {
	private $vars = array();
	private $values = array();
	private $properties = array();
	private $instances = array();
	private $blocks = array();
	private $parents = array();
	private $accurate;
	private $erros_template;
	//private $filename;
	
	private static $REG_NAME = "([[:alnum:]]|_)+";
	
		 
	
	public function __construct($filename, $string = null ,$accurate = false){
		$this->accurate = $accurate;
		//$html = @$html;
		
		if ($filename == "texto")
		$this->ler_texto($string);
		else{
		
		/* if ($GLOBALS['servidor'] == "on"){
			$arqui = file_get_contents($filename);
			if (!preg_match_all("", $arqui, $r)){
			$limpo = $this->limpa_html($arqui);
			file_put_contents($filename, "" . $limpo);}
			} */
			
		$this->loadfile(".", $filename);
        $GLOBALS['filename'] = $filename;
		}
	}

	/**
	 * Adiciona o conteúdo do arquivo identificado por $filename na variável de template 
	 * identificada por $varname
	 *
	 * @param     string $varname		uma variável de template existente
	 * @param     string $filename		arquivo a ser carregado
	 */
	public function addFile($varname, $filename){
	
		if(!$this->existe_var($varname)) throw new InvalidArgumentException("addFile: var $varname não existe");
		
		/* if ($GLOBALS['servidor'] == "on"){
			$arqui = file_get_contents($filename);
			if (!preg_match_all("", $arqui, $r)){
			$limpo = $this->limpa_html($arqui);
			file_put_contents($filename, "" . $limpo);}
			} */
			
		$this->loadfile($varname, $filename);
	}
	
	/**
	 * Não use este método, ele serve apenas para podemos acessar as variáveis 
	 * de template diretamente.
	 *
	 * @param	string	$varname	template var name
	 * @param	mixed	$value		template var value
	 */
	public function __set($varname, $value){

		if(!$this->existe_var($varname))
		$this->erros_template = "<u>*AVISO</u>: A variavel $varname não existe no arquivo: <i>". $GLOBALS['filename'] ."</i>" . "<br />" . @$this->erros_template;
		

		 $stringValue = $value;
		if(is_object($value)){
			$this->instances[$varname] = $value;
			if(!array_key_existe_var($varname, $this->properties)) $this->properties[$varname] = array();
			if(method_existe_var($value, "__toString")) $stringValue = $value->__toString();
			else $stringValue = "Object";
		} 
		 
		
		$this->setValue($varname, $stringValue);
		
		return $value;
	}
	
	
	/**
	 * Não use este método, ele serve apenas para podemos acessar as variáveis 
	 * de template diretamente.
	 *
	 * @param	string	$varname	template var name
	 */
	public function __get($varname){
		if (isset($this->values["{".$varname."}"]))
			return $this->values["{".$varname."}"];
			else
			echo ("AVISO: A variavel $varname não existe!!");
	}

	/**
	 * Verifica se uma variável de template existe.
	 *
	 * Retorna true se a variável existe. Caso contrário, retorna false.
	 *
	 * @param	string	$varname	template var name
	 */
	public function existe_var($varname){
		return in_array($varname, $this->vars);
	}
    public function existe_bloco($blockname){
        return in_array($blockname, $this->blocks);
    }

	public function exibirBlocos(){
		
		while (list($key, $val) = each($this->vars)) { 
		
			if (@$teste == "")
				$teste ="Todos os Blocos: $val"; 
				else
				$teste = @$teste . ", " . $val  ;
			}

		$this->erros_template =  $teste;        
    }
	/**
	 * Loads a file identified by $filename.
	 * 
	 * The file will be loaded and the file's contents will be assigned as the 
	 * variable's value.
	 * Additionally, this method call Template::recognize() that identifies 
	 * all blocks and variables automatically.
	 *
	 * @param     string $varname		contains the name of a variable to load
	 * @param     string $filename		file name to be loaded
	 * 
	 * @return    void
	 */
	private function loadfile($varname, $filename) {
		if (!file_exists($filename)){
			echo "<font COLOR='#f00'><u>*AVISO</u>: O Arquivo <i>$filename</i> não existe!!</font><br />". @$this->erros_template;
			
			exit;
			}else{
			// Reading file and hiding comments
			$str = preg_replace("//smi", "", file_get_contents($filename));
			
			$str = preg_replace("//smi", "", file_get_contents($filename));
			
			
			$blocks = $this->recognize($str, $varname);
			if (empty($str))
				echo "<font COLOR='#f00'><u>*AVISO</u>: O Arquivo <i>$filename</i> está vazio!!</font><br />". @$this->erros_template;
			
			
			$this->setValue($varname, $str);
			
			$this->createBlocks($blocks, $filename);}
	}

#condtec 17-9-2013
public function ler_texto($texto){
		// Reading file and hiding comments
			$str = preg_replace("//smi", "", $texto);
			
			$str = preg_replace("//smi", "", $texto);
			
			
			$blocks = $this->recognize($str, ".");
			if (empty($str))
				echo "<font COLOR='#f00'><u>*AVISO</u>: O Texto está vazio!!</font><br />". @$this->erros_template;
			
			
			$this->setValue(".", $str);
			
			$this->createBlocks($blocks, "texto");
	}
	
#condtec 11-9-2013
public function add_string($varname, $string){
		if(!$this->existe_var($varname)) throw new InvalidArgumentException("add_string: A var $varname não existe");
		$this->abrir_string($varname, $string);
	}
#condtec 11-9-2013	
private function abrir_string($varname, $string) {
		if ($string == ""){
			echo "<font COLOR='#f00'><u>*AVISO</u>: A string esta vazia!!</font><br />". @$this->erros_template;
			exit;
			}else{
			// Reading file and hiding comments
			$str = preg_replace("//smi", "", $string);
			
			
			$blocks = $this->recognize($str, $varname);
			if (empty($str))
				echo "<font COLOR='#f00'><u>*AVISO</u>: O Arquivo <i>$string</i> está vazio!!</font><br />". @$this->erros_template;
			
			
			$this->setValue($varname, $str);
			
			$this->createBlocks($blocks, $string);}
	}
	
	
function organiza($tudo ,$html=0, $css=0,$java=0){  
		
		
	return $this->limpa_html($tudo ) ;
	
	}
	
#----------------------------------------------------------------------

	function limpa_css($css){  
	$css = str_replace('; ',';',str_replace(' }','}',str_replace('{ ','{',str_replace(array("\r\n","\r","\n","\t",'  ','    ','    '),"",preg_replace('!/\*[^*]*\*+([^/][^*]*\*+)*/!','',$css))))); 
	return $css;
	}
	
	
function limpa_html($html){
	preg_match_all('!(&lt;(?:code|pre).*&gt;[^&lt;]+&lt;/(?:code|pre)&gt;)!',$html,$pre);#exclude pre or code tags<br />
	$html = preg_replace('!&lt;(?:code|pre).*&gt;[^&lt;]+&lt;/(?:code|pre)&gt;!', '#pre#', $html);#removing all pre or code tags<br />
	$html = preg_replace('#&lt;!--[^\[].+--&gt;#', '', $html);#removing HTML comments<br />
	$html = preg_replace('/[\r\n\t]+/', ' ', $html);#remove new lines, spaces, tabs<br />
	$html = preg_replace('/&gt;[\s]+&lt;/', '&gt;&lt;', $html);#remove new lines, spaces, tabs<br />
	$html = preg_replace('/[\s]+/', ' ', $html);#remove new lines, spaces, tabs<br />
	if(!empty($pre[0]))
		foreach($pre[0] as $tag)
	$html = preg_replace('!#pre#!', $tag, $html,1);#putting back pre|code tags<br />
	return $html;
	}
	
	
	
	/**
	 * Identify all blocks and variables automatically and return them.
	 * 
	 * All variables and blocks are already identified at the moment when 
	 * user calls Template::setFile(). This method calls Template::identifyVars() 
	 * and Template::identifyBlocks() methods to do the job.
	 *
	 * @param     string	$content		file content
	 * @param     string	$varname		contains the variable name of the file
	 * 
	 * @return    array		an array where the key is the block name and the value is an 
	 * 						array with the children block names.
	 */
	private function recognize(&$content, $varname){
		$blocks = array();
		$queued_blocks = array();
		foreach (explode("/sm";
		preg_match($reg, $line, $m);
		if (1==preg_match($reg, $line, $m)){
			if (0==sizeof($queued_blocks)) $parent = $varname;
			else $parent = end($queued_blocks);
			if (!isset($blocks[$parent])){
				$blocks[$parent] = array();
			}
			$blocks[$parent][] = $m[1];
			$queued_blocks[] = $m[1];
		}
		$reg = "//sm";
		if (1==preg_match($reg, $line)) array_pop($queued_blocks);
	}
	
	/**
	 * Identifies all variables defined in the document.
	 *
	 * @param     string $line				contains one line of the content file
	 */
	private function identifyVars(&$line){
		$r = preg_match_all("/{(".self::$REG_NAME.")((\-\>(".self::$REG_NAME."))*)?}/", $line, $m);
		if ($r){
			for($i=0; $i<$r; $i++){
				// Object var detected
				if($m[3][$i] && (!array_key_existe_var($m[1][$i], $this->properties) || !in_array($m[3][$i], $this->properties[$m[1][$i]]))){
					$this->properties[$m[1][$i]][] = $m[3][$i];
				}
				if(!in_array($m[1][$i], $this->vars)) $this->vars[] = $m[1][$i];
			}
		}
	}
	
	/**
	 * Create all identified blocks given by Template::identifyBlocks().
	 *
	 * @param     array $blocks		contains all identified block names
	 * @return    void
	 */
	private function createBlocks(&$blocks, $filename) {
		$this->parents = array_merge($this->parents, $blocks);
		foreach($blocks as $parent => $block){
			foreach($block as $chield){
				/*
				if(in_array($chield, $this->blocks)) {
				$this->erros_template = "Bloco duplicado ($chield) no arquivo: <i>". $filename ."</i><br />". @$this->erros_template;
				$this->show();
				//exit;
				}*/
				
				$this->blocks[] = $chield;
				$this->setBlock($parent, $chield,$filename);
			}
		}
	}
	
	/**
	 * A variable $parent may contain a variable block defined by:
	 * &lt;!-- INI $varname --&gt; content &lt;!-- FIM $varname --&gt;. 
	 * 
	 * This method removes that block from $parent and replaces it with a variable 
	 * reference named $block. The block is inserted into the varKeys and varValues 
	 * hashes. 
	 * Blocks may be nested.
	 *
	 * @param     string $parent	contains the name of the parent variable
	 * @param     string $block		contains the name of the block to be replaced
	 * @return    void
	 */
	private function setBlock($parent, $block,$filename) {
		$name = "B_".$block;
		$str = $this->getVar($parent);
		if($this->accurate){
			$str = str_replace("\r\n", "\n", $str);
			$reg = "/\t*\n*(\s*.*?\n?)\t*\n?/sm";
		} 
		else $reg = "/\s*(\s*.*?\s*)\s*/sm";
		if(1!==preg_match($reg, $str, $m)) {
			$this->erros_template = "<font COLOR='#f00'><u>*AVISO</u>: O Bloco $block esta mal formatado em <i>$filename</i>, tem que ser montado da seguinte maneira:</font> <br /><br />
			&lt;!-- INI $block --&gt;<br />
				&nbsp;&nbsp;&nbsp;&nbsp;{BLOCOS}<br />
			&lt;!-- FIM $block --&gt; 
			" . "<br />" . @$this->erros_template;
			//$this->show();
			//echo "Bloco <b>$block</b> está mal formado!! ";
			
			//exit;
			}
		
		$this->setValue($name, '');
		@$this->setValue($block, $m[1]);
		$this->setValue($parent, preg_replace($reg, "{".$name."}", $str));
	}

	/**
	 * Internal setValue() method.
	 *
	 * The main difference between this and Template::__set() method is this 
	 * method cannot be called by the user, and can be called using variables or 
	 * blocks as parameters.
	 *
	 * @param     string $varname		constains a varname
	 * @param     string $value        constains the new value for the variable
	 * @return    void
	 */
	private function setValue($varname, $value) {			
			$this->values["{".$varname."}"] = $value;
		}
	
	/**
	 * Returns the value of the variable identified by $varname.
	 *
	 * @param     string	$varname	the name of the variable to get the value of
	 * @return    string	the value of the variable passed as argument
	 */
	private function getVar($varname) {
	
		return $this->values['{'.$varname.'}'];
	
	}
	
	/**
	 * Limpa o valor de uma variável
	 * 
 	 * O mesmo que $this->setValue($varname, "");
	 *
	 * @param     string $varname	nome da variável
	 */
	public function clear($varname) {
		$this->setValue($varname, "");
	}
	
	/**
	 * Fill in all the variables contained within the variable named
	 * $varname. The resulting value is returned as the function result and the
	 * original value of the variable varname is not changed. The resulting string
	 * is not "finished", that is, the unresolved variable name policy has not been
	 * applied yet.
	 *
	 * @param     string 	$varname      the name of the variable within which variables are to be substituted
	 * @return    string	the value of the variable $varname with all variables substituted.
	 */
	function subst($varname) {
		$s = $this->getVar($varname);
		// Common variables replacement
		$s = str_replace(array_keys($this->values), $this->values, $s);
		// Object variables replacement
		foreach($this->instances as $var => $instance){
			foreach($this->properties[$var] as $properties){
				if(false!==strpos($s, "{".$var.$properties."}")){
					$pointer = $instance;
					$property = explode("->", $properties);
					for($i = 1; $i < sizeof($property); $i++){
						$obj = str_replace('_', '', $property[$i]);
						// Non boolean accessor
						if(method_existe_var($pointer, "get$obj")){
							$pointer = $pointer->{"get$obj"}();
						}
						// Boolean accessor
						elseif(method_existe_var($pointer, "is$obj")){
							$pointer = $pointer->{"is$obj"}();
						}
						// Magic __get accessor
						elseif(method_existe_var($pointer, "__get")){
							$pointer = $pointer->__get($property[$i]);
						}
						// Accessor dot not existe_var: throw Exception
						else {
							$className = $property[$i-1] ? $property[$i-1] : get_class($instance);
							$class = is_null($pointer) ? "NULL" : get_class($pointer);
							throw new BadMethodCallException("não existe método na classe ".$class." para acessar ".$className."->".$property[$i]);
						}
					}
					// Checking if final value is an object
					if(is_object($pointer)){
						if(method_existe_var($pointer, "__toString")){
							$pointer = $pointer->__toString();
						} else {
							$pointer = "Object";
						}
					}
					// Replace
					$s = str_replace("{".$var.$properties."}", $pointer, $s);
				}
			}
		}
		return $s;
	}
	
	/**
	 * Clear all child blocks of a given block.
	 *
	 * @param     string $block	a block with chield blocks.
	 */
	private function clearBlocks($block) {
		if (isset($this->parents[$block])){
			$chields = $this->parents[$block];
			foreach($chields as $chield){
				$this->clear("B_".$chield);
			}
		}
	}
	
	/**
	 * Mostra um bloco.
	 * 
	 * Esse método deve ser chamado quando um bloco deve ser mostrado.
	 * Sem isso, o bloco não irá aparecer no conteúdo final.
	 *
	 * Se o parâmetro $append for true, o conteúdo do bloco será 
	 * adicionado ao conteúdo que já existia antes. Ou seja, use true 
	 * quando quiser que o bloco seja duplicado.
	 *
	 * @param     string $block		nome do bloco que deve ser mostrado
	 * @param     boolean $append		true se o conteúdo anterior deve ser mantido (ou seja, para duplicar o bloco)
	 */
	public function block($block, $append = true) {
		if(!in_array($block, $this->blocks))
			$this->erros_template = "<u>*AVISO</u>: O Bloco $block não existe no arquivo: <i>". $GLOBALS['filename'] ."</i>" . "<br />" . @$this->erros_template;
		else
		//("AVISO: O Bloco $block não existe!!");
		if ($append) $this->setValue("B_".$block, $this->getVar("B_".$block) . $this->subst($block));
		else 
		$this->setValue("B_".$block, $this->subst($block));
		$this->clearBlocks($block);
	}
	
	/**
	* Retorna o conteúdo final, sem mostrá-lo na tela. 
	* Se você quer mostrá-lo na tela, use o método Template::show().
	* 
	* @return    string	
	*/
	public function parse($mostrar_blocos) {
		// After subst, remove empty vars
		// echo $mostrar_blocos;
		#condtec 31-01 mostra os blocos		
		if(@$mostrar_blocos == 0)
			return preg_replace("/{(".self::$REG_NAME.")((\-\>(".self::$REG_NAME."))*)?}/", "", $this->subst("."));
			else
			return $this->subst(".");
	}

	/**
	 * Mostra na tela o conteúdo final.
	 */
	 public function exibir($var) {
		$this->erros_template = @$var;
	}
	public function show($mostrar_blocos=0) {
		
		if ($this->existe_var("ERROS_TEMPLATE"))
		if ($this->erros_template != ""){
			$this-> ERROS_TEMPLATE = $this->erros_template;
			if ($this->existe_bloco("B_ERROS_TEMPLATE"))
				$this->block("B_ERROS_TEMPLATE");
			}else
			echo $this->erros_template;
			
			
				
				echo $this->parse($mostrar_blocos);
		
	}
}
?>`
