### ISSUE TITLE
How to ignore certain vars inside {}

### ISSUE THREAD

**Issue by pulketo** [raelgc/template#27]
I need to ignore certain variables (pass them as is).
some javascript vars are encoded like this {x}/{y}

**Comment by raelgc** [comment]
Hi @pulketo, you can do something like this:

    {{_}x}/{{_}y}

Yeap, I know it's ugly...

**Comment by condtec** [comment]
just do this: {{X}} / {{y}} or put your java script code in a variable.

**Comment by condtec** [comment]
Rael só como sugestão, teria como mostrar os blocos não usados, e tbm só validar blocos com letras maiúsculas?

**Comment by raelgc** [comment]
@condtec: Possível sempre é, mas teria que pensar numa forma de não quebrar a compatibilidade. Talvez um método pra forçar mostrar todos os blocos? Mas se for o caso, por favor, abra um novo issue.
