### ISSUE TITLE
Atualizar markdown do README

### ISSUE THREAD

**Issue by raelgc** [raelgc/template#28]
Vários trechos de código do arquivo README estão sem a sintaxe colorida, principalmente os trechos em HTML.

Reduzir também o tamanho do espaçamento/tabulação para apenas 2 espaços, para ajudar na leitura em telas menores.

**Comment by vaneves** [comment]
@raelgc para ficar colorido, deve informar qual a linguagem, por exemplo:

&grave;&grave;&grave;html
&lt;p class="text"&gt;&lt;p/&gt;
&grave;&grave;&grave;

Em alguns lugares o "código" está apenas com tab, mas o ideal é usar a sintaxe acima.

**Comment by raelgc** [comment]
Sim, exatamente o que estou fazendo. Basicamente todas as seções HTML estão sem a informação de linguagem.
