### ISSUE TITLE
Erro ao utilizar o template

### ISSUE THREAD

**Issue by JulianoGaspar** [raelgc/template#31]
Caro Rael, primeiro, meus parabéns, adoro usar sua classe a muito tempo, hoje em dia indico pros meus alunos também.

Entretanto estou com um problema a algumas semanas que não consegui perceber onde esta o problema. Percebi que ao incluir determinadas linhas de HTML a mais o template não está rodando. E aparecendo seguinte mensagem:

Fatal error: Uncaught exception 'UnexpectedValueException' with message 'mal-formed block BLOCK_LINHA_TABLE_CAD_PACIENTE' in /www/clinicaltrials_dev/lib/raelgc/view/Template.php:318 Stack trace: #0 /www/clinicaltrials_dev/lib/raelgc/view/Template.php(293): raelgc\view\Template->setBlock('.', 'BLOCK_LINHA_TAB...') #1 /www/clinicaltrials_dev/lib/raelgc/view/Template.php(187): raelgc\view\Template->createBlocks(Array) #2 /www/clinicaltrials_dev/lib/raelgc/view/Template.php(104): raelgc\view\Template->loadfile('.', 'cad_pacientes.h...') #3 /www/clinicaltrials_dev/paginas/cad_pacientes.php(16): raelgc\view\Template->__construct('cad_pacientes.h...') #4 {main} thrown in /www/clinicaltrials_dev/lib/raelgc/view/Template.php on line 318

Vi sua observação sobre blocos malformados, mas não é esse o problema.
Pois basta apagar uma linha qualquer como um LABEL o template funciona.

Você já passou por isso?

**Comment by raelgc** [comment]
Oi @JulianoGaspar, já sim. Lembro que é algum limite do PHP em relação a String passada na expressão regular.

Tem como você separar o arquivo HTML problemático em duas partes pra ver se resolve?

**Comment by JulianoGaspar** [comment]
Ei @raelgc  cara é um gênio.
Funcionou sim! Nunca havia pensando em utilizar assim.
Vou continuar testando, se houver algum problema posto aki.
Obrigado mais uma vez!

Como resolvi:

```
$tpl = new Template("painel_estudos.html");
$tpl->addFile("MODAL", "painel_estudos_modal.html");
```
