### ISSUE TITLE
propriedades de objetos com camelcase ou snakecase não é aceito

### ISSUE THREAD

**Issue by masakik** [raelgc/template#32]
Notei que na linha 417 
```
$obj = strtolower(str_replace('_', '', $property[$i]));
```
a biblioteca limita isso.
Algum motivo?
Obrigado.

**Comment by raelgc** [comment]
Oi @masakik.

Estou assumindo que no HTML as propriedades estarão caixa alta, como `{OBJETO->PROPRIEDADE}`.

Daí nessa linha, a classe testa nessa ordem:

- se a classe `Objeto` tem um método `getPropriedade` (quando eu testei, aqui tanto faz se o método tem caixa alta ou não, pode ser `getpropriedade` ou qualquer variação... mas talvez isso tenha mudado nas versões mais novas do PHP, e talvez aqui esteja a origem do seu probelma) 

- se a classe tem o método "mágico" `__get`: aí a classe chama `__get($propriedade)`

- se a classe tem um atributo chamado `$propriedade`

Pelo que eu entendi, seu problema é que o primeiro teste não está funcionando corretamente, certo?

**Comment by masakik** [comment]
Ola,
no meu método tem propriedade 'minha_propriedade' em snakecase, aí não funciona.

**Comment by masakik** [comment]
é uma stdClass(), sem métodos.

**Comment by masakik** [comment]
é o terceiro caso, se a classe tem um atributo chamado $propriedade

**Comment by masakik** [comment]
e se criar uma constante que configura o template para não assumir que estão em caixa alta? deixa o padrão como está e se estiver setado algo tipo TEMPLATE_PRESERVE_CASE = true ele não aplica as modificações de case e "_".

**Comment by raelgc** [comment]
Hm, entendi. Talvez a gente possa simplesmente adicionar esse caso na checagem.

**Comment by masakik** [comment]
quer que eu faça um pull request?

**Comment by raelgc** [comment]
Se você puder, será ótimo! Não se esqueça de mudar a versão pra `2.2.4` e adicionar uma entrada no arquivo CHANGELOG.
