### ISSUE TITLE
Documentação sobre objetos

### ISSUE THREAD

**Issue by masakik** [raelgc/template#36]
Na documentação:
"A instrução P->NAME chamará o método $p->getName(), caso ele exista. Se não existir esse método na classe, um erro será disparado.
Isso vale para qualquer atributo que tentarmos chamar no HTML: será traduzido para $meuObjeto->getAtributo(). Se o nome do método PHP for composto, como por exemplo $p->getExpirationDate(), basta usar underscore _ no HTML como separador dos nomes: no caso do exemplo, ficaria P->EXPIRATION_DATE."

A substituição de P->NAME para $p->getName() não creio que funcione por causa da linha 416 
`$obj = strtolower(str_replace('_', '', $property[$i]));`
Que também afeta o uso de underscore no nome dos atributos do objeto.

**Comment by raelgc** [comment]
Na linha 418:

```php
if(method_exists($pointer, "get$obj"))
```

Então `P->EXPIRATION_DATE` será transformado em `$p->getexpirationdate()`, que até onde eu tenha testado (na época), era case insensitive.

**Comment by masakik** [comment]
Realmente se for um método é case insensitive mas se for atributo é case sensitive. Então #32 resolveu isso também. Valeu.

**Comment by raelgc** [comment]
Obrigado você pelo interesse e toda ajuda, @masakik! :)
