### ISSUE TITLE
quando usamos objetos e modificadores o objeto  não é passado corretamente ao modificador

### ISSUE THREAD

**Issue by masakik** [raelgc/template#38]
Isso ocorre na linha 438 que se o objeto não possuir o método __toString então ele vai passar a string 'Object' para o modificador na linha 453.
Eu fiz $pointer2 = $pointer e passei $pointer2 para funcionar. Alguma idéia melhor de como tratar esse caso?

**Comment by raelgc** [comment]
O que vai ser impresso nesse caso da mudança?

Explicando o código atual: originalmente eu deixei pro próprio PHP tratar o objeto. Ele vai transformar o Object em String como seria numa página padrão. Acrescentei apenas a checagem por `__toString`, porque achei que ele fizesse isso, como em outras linguagens (já que não faz - ou na época, não fazia, não testei mais - acrescentei).

**Comment by masakik** [comment]
eu estou usando json_encode no objeto para converter em string nesse caso específico

**Comment by raelgc** [comment]
Gostei! Pode mandar um PR disso, fazendo bump de minor version e incluindo no changelog?

**Comment by masakik** [comment]
nesse caso mudaria o comportamento padrão para exibir o json ou somente uma modificação para passar o parâmetro correto para o modificador?

**Comment by raelgc** [comment]
Primeiro caso: exibir json somente quando seria exibido "Object". O resto deve seguir do jeito que está, inclusive a checagem da existência por `__toString`.

**Comment by masakik** [comment]
Veja se esta  bom.

**Comment by raelgc** [comment]
Ficou ótimo! Obrigado mais uma vez, @masakik!
