### ISSUE TITLE
Valor em branco quando usa addFile

### ISSUE THREAD

**Issue by rafaelkapela** [raelgc/template#4]
Sempre quando incluo um addFile, no arquivo final é colocado alguns espaços antes do arquivo importado pelo addFile.

O Chrome mostra os caracteres "&#65279;    " antes do arquivo, o que gera uma exibição de um espaço em branco no html final

**Comment by raelgc** [comment]
Oi @rafaelkapela!

No construtor, ao invés de fazer:

```php
    $tpl = new Template('meuarquivo.html');
```

Faça:

```php
    $tpl = new Template('meuarquivo.html', true);
```

**Comment by rafaelkapela** [comment]
Valeu @raelgc. Acabei resolvendo com truques de css3 mesmo. Mas, na próxima, vou usar este true. 
Tenho um segundo issue, vou abrir outro tópico.
