### ISSUE TITLE
Implement a test suite

### ISSUE THREAD

**Issue by raelgc** [raelgc/template#42]
- [x] minimal phpunit integration
- [x] simple var
- [x] var exists/not exists
- [x] modifiers
- [x] empty block
- [x] simple block
- [x] nested block
- [x] finally block
- [x] clear method in select 
- [x] multiple files
- [x] simple object
- [x] different object calling methods: `$property` , `get<property>()`, `__get`, `__toString`, `Object` 
- [x] comments
- [x] escaped vars
- [ ] error messages
- [ ] accurate mode

Let's not repeat release 2.2.6.

**Comment by raelgc** [comment]
This will involve:
- write some specs using PHP Unit
- setup a CI (in a free tier account)
- have this CI running on any PR
- put the current CI status on README

**Comment by vaneves** [comment]
Circle is free: https://circleci.com/pricing/

**Comment by masakik** [comment]
Hi, I´m not fluent in phpunit but if you create the basic structure I can contribute with specific tests.

**Comment by raelgc** [comment]
Cool! I'll work on to create the basic structure this week.

**Comment by raelgc** [comment]
Just pushed a draft of this on branch [`42-tests`](https://github.com/raelgc/template/compare/42-tests)

**Comment by masakik** [comment]
- [x] simple var
- [x] simple object
- [ ] basic block
- [ ] nesed block
- [ ] finally block
- [ ] multiple files

**Comment by raelgc** [comment]
I just pushed a commit downgrading PHP Unit to support PHP 5 and removing the type coercion.

**Comment by raelgc** [comment]
I pushed the empty and simple block test cases too. Please, remember to run a `git pull` before add new test cases.

**Comment by masakik** [comment]
You missed simple_block.html file.

**Comment by masakik** [comment]
Is it reasonable use phpunit requirement something like ^5 || ^6 || ^7 || ^8 to support all versions of php?

**Comment by raelgc** [comment]
@masakik I just pushed the missing file, thanks for the warning.

About the requirement version for PHPUnit: I think we should keep the lowest denominator here. My concern is if we introduce any syntax on tests that is not valid in old versions and miss that due the fact we're using a new version.

**Comment by raelgc** [comment]
I just added all the property and getter tests. I think this is enough to start to setup a CI environment. The only downside is that I had to use anonymous classes and I think this is available only on PHP >= 7.
