### ISSUE TITLE
Array no Template

### ISSUE THREAD

**Issue by rafaelkapela** [raelgc/template#7]
Olá @raelgc.
É possível exibir um array diretamente no template? Explico:
**arquivo.php**
`$tpl->arrayTeste = array("nome"->"a","nascimento"->"b","algomais" -> "c")`

**template.html**
`Este é um array: {arrayTeste[nome]}` ou `Este é um array: {arrayTeste->nome}`

**Comment by rafaelkapela** [comment]
E aí @raelgc ... Alguma posição? hehe

**Comment by raelgc** [comment]
@rafaelkapela Desculpe mesmo pela demora... além dos trabalhos e projetos open-source, a família inteira ficou doente essa semana, então acabei deixando os projetos open-source um pouco de lado.

Mas vamos lá: atualmente isso não é suportado, mas acredito que não seja muito difícil incluir esse suporte.

O único contra seria uma pequena demora adicional no parsing, mas nada demais também.

**Comment by rafaelkapela** [comment]
Valeu pela resposta @raelgc ... Eu até tentei implementar, mas meus conhecimentos são mais limitados, hehe...
Quando puder, faça a alteração. Vai ajudar bastante! Obrigado

**Comment by Valkhan** [comment]
@rafaelkapela Poderia me citar um exemplo prático desta sua solicitação, pois para exibir informações dentro de um array de forma repetida, podemos usar o recurso de blocos que já tem na classe. Talvez não tenha compreendido o objetivo que tenha em mente.
