### ISSUE TITLE
Aplicar os PSRs

### ISSUE THREAD

**Issue by vaneves** [raelgc/template#9]
Seria interessante padronizar o código de acordo com as PSRs (PHP Standard Recommendation)
- Colocar a classe dentro do diretório `src/raelgc/view`;
- Aplicar PSR 1, 2 e 4;
- Criar um arquivo composer.json;
- Importar o projeto no Packagist;

**Comment by raelgc** [comment]
@vaneves, realmente, uma ótima idéia. Na época eu apliquei apenas o PSR0, que, se não me engano, foi o que me motivou a colocar dentro de `/raelgc/view`.

Você consegue/sabe criar um pull request com as alterações dos itens 1 e 2?

**Comment by vaneves** [comment]
Sim, tranquilo.
